language: node_js
node_js:
  - 12.18.
  
branches:
  only:
  - main

services:
  docker

script:
  - docker --version
  - docker build --rm -t udagram-user-api
  - docker tag udagram-user-api elsrickle/udagram-user-api:latest

after_success:
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push elsrickle/udagram-user-api