language: node_js
node_js:
  - 12.18.
  
branches:
  only:
  - main

services:
  npm
  docker

script:
  - npm -v
  - npm run build
  - docker --version
  - docker build -t udagram-user-api .
  - docker tag udagram-user-api elsrickle/udagram-user-api:latest

after_success:
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push elsrickle/udagram-user-api